### ISSUE TITLE
[vscode] Sign in with Slack failed: access_denied

### ISSUE THREAD

**Issue by seeward** [karigari/vscode-chat#123]
Sign in with Slack failed: access_denied

- Extension Version: 0.5.9
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
Hi @seeward, thanks for reporting this. This typically happens if your slack workspace permissions require one of your admins to approve apps before they can be installed. You can share the following link with your team admins to get an approval. Let me know if there's anything we could do to help you with this

https://slack.com/apps/ACB4LQKN1-slack-chat-for-vs-code

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. Will close this issue for now - please feel free to create a new one if I have missed anything.
