### ISSUE TITLE
Allow custom server for authentication and Slack integration

### ISSUE THREAD

**Issue by jasonwilczak** [karigari/vscode-chat#143]
So this is more of an "walled garden" type request.  

There is concern from security that the extension runs a connection to a 3rd party server hosted by the developer of the Slack application.  There is no visibility into the server or how it functions and it uses an OAuth token to authenticate to Slack and post/do stuff on the user's behalf.

Is it sufficiently possibly to allow us to control the server part?  Like if we stood up our own endpoint to do the work?

**Comment by arjun27** [comment]
Thanks for sharing this concern @jasonwilczak. The third party server (which runs on https://vscode.chat) handles the OAuth redirection only. The service does not store the token anywhere - just passes it from slack to the extension. This was required because slack does not let non-http redirections on OAuth. You can verify this in the source code of the service here: https://github.com/karigari/vscode-chat/tree/master/oauth-service. Happy to point you to the right areas if you'd like to review.

You can also host this service on your own, and create a new "slack application" with your custom redirection endpoint.

**Comment by arjun27** [comment]
A custom endpoint would not require any changes in the extension config actually. Let me list down the changes required

1. Create a new slack application and get the client id and secret
2. Deploy the oauth service, and set the client id and secret as environment variables
3. Define the url of the oauth service as the redirection url for the slack app
4. Open the authorization url of the slack application, which will redirect to the oauth service, and then redirect to the vscode extension

**Comment by arjun27** [comment]
@jasonwilczak - let me know if there's anything else you would need here. I'm closing this issue for now.
