### ISSUE TITLE
Deleted users from slack workspace still showing up as direct message options

### ISSUE THREAD

**Issue by tristan957** [karigari/vscode-chat#172]
I am seeing users that I deleted from my slack workspace as direct message options in Team Chat.

**Comment by arjun27** [comment]
Thanks for reporting this @tristan957. The DM channel entities on Slack are not deleted when the users are deleted. We could however handle this situation by validating whether the users exist as an additional check.

Just to confirm - are these DM channels referred by the user ids instead of user names? Would look something like @UABCD1213

**Comment by tristan957** [comment]
I am going to create the PR. I can't seem to sign in to the extension for some reason on Linux though. It worked fine on Mac earlier.

**Comment by arjun27** [comment]
Thanks @tristan957, the change looks good, and I'll merge before the next release. Do you see any logs for the auth issue on Linux? My hunch is that it is related to keytar requirements for Linux as given here: https://github.com/atom/node-keytar#on-linux

To check logs, you can
- See output channel by the name of "Team Chat"
- Run the "toggle developer tools" command on vscode
- Run the "open developer tools for web view" command on vscode, when the chat window is open

**Comment by arjun27** [comment]
hi @tristan957 – I'm releasing this fix in v0.6.2. thanks for the PR! I made some more changes on top of your changes in #200, to hide DMs and groups that have deleted users
