### ISSUE TITLE
Onboarding: simplify chat provider selection

### ISSUE THREAD

**Issue by arjun27** [karigari/vscode-chat#197]
If the user does not select a chat provider in the "configure token" step, the extension goes into a random state that is hard to discover. We need a better ux to handle this scenario

**Comment by mittalyashu** [comment]
Instead of using 3 different icons use a single icon.

When I install the vscode-chat for the first time I saw a different icon in the sidebar but when I login to discord I see different icon. But the problem doesn't end here...

**Watch this video:** https://youtu.be/C-xXtUremUc _(watch the icon carefully)_

**Comment by arjun27** [comment]
Onboarding flow has been updated to fix this.
