### ISSUE TITLE
Enable reverse-initiating a Live Share session via a “/live request” command

### ISSUE THREAD

**Issue by lostintangent** [karigari/vscode-chat#21]
Currently, Live Share enables developers to easily share their workspace, and coordinate a collaboration session with someone by sending them the session URL. The “/live share” command simplifies this workflow by enabling an in-chat experience for establishing that interaction.

However, there are instances where someone might want to review your code, or collaborate with you, but they would be the “guest” and not the “host”. To simplify the experience for enabling such a workflow, we could implement a “/live request” command, which would send a request to the recipient to share their current project via Live Share. If the recipient accepted, it would automatically share their project, and then automatically join the sender. This would dramatically simplify the act of “reverse initiating” a Live Share session, and is likely best enabled by a chat solution like this.

**Comment by arjun27** [comment]
Reverse initiation is a great idea. I've found myself asking people to start a session, and this will simplify that. I have released v0.4.0 with an early implementation of `/live request`.

![mgwjsa2j5h](https://user-images.githubusercontent.com/284612/42387394-c61b8bf4-815f-11e8-9c02-c1bb872560d2.gif)

There are some improvements/questions as a result of my first impressions on the flow. I'm planning to iron them out with the next few releases. Specifically,

1. I've kept the implementation stateless right now, but that can create some unintuitive scenarios. For example, multiple `/live request` in the same channel means multiple "Accept" links - clicking any of which will start a session. There is no state around the link being "accepted", and perhaps expired. I don't think that is required...
2. ...except for giving interaction feedback. While clicking on "accept" triggers the "Sharing..." in the status bar, it can be easily missed in normal usage - which keeps the user really hanging, and feels incomplete. Need to evaluate if others feel the need for this feedback too, and add that. Perhaps we could mimic the Slack app [message buttons behavior](https://api.slack.com/docs/message-buttons)
3. The initiator can auto-join the Live Share link as you have suggested - I was thinking of checking for the following condition: "if live share URL received and `/live request` sent by user in the last 15 mins, then auto-join"
4. Currently, joining the link reloads the VS Code window and loads the remote project. With an explicit click to join, this seems ok. But with auto-join, the window will reload itself on receiving a message, and might appear arbitrary to the user. Reloading the window also removes the Slack webview, which makes it look like a completely new context. Due to this, I'm not sure if auto-joining will give the correct user experience. Any thoughts on how to improve this?

I'm going to use `/live request` more in my day-to-day use, and see if that changes my early impressions. Would love to hear thoughts from everyone so that we can make this a great experience!

**Comment by arjun27** [comment]
Some more food for thought: I was going through the original issue on this (https://github.com/MicrosoftDocs/live-share/issues/422), and realized we could leverage the [Slack presence API](https://api.slack.com/docs/presence-and-status) for peer discovery. The API has a custom status field that can show active project label, or even the session URL. What do you think?

**Comment by lostintangent** [comment]
Some thoughts based on your comments:

1. What if we added a "Dismiss" link, that would expire/invalidate the request. That way, anytime an action was taken on the request (either accept or dismiss), the message would "invalidate".

2. I also like the suggestion of mimicking the message button behavior. From a UI-perspective, it might also look nicer to render buttons, as opposed to links. But thats lower priority

3. As I think about it, I'm not sure whether auto-joining makes total sense, so we should just hold off on that for now, and get a feel for the experience.

Regarding the user presence comment, I'd definitely love to discuss this! We actually started discussing whether Live Share should provide an abstract concept of user presence, that would allow extensions to implement 1) list of users, 2) whether those users are available, 3) a mechanism to communicate the share session with them. That way, Live Share itself could allow you to share with someone, using different communication mechanisms under the covers. I'd love to discuss this further!

**Comment by arjun27** [comment]
I was exploring how we could improve the initialization flow by using user presence, and came up with this implementation that uses Slack as a background transport channel (not as a chat window).

![ucpgxobrla](https://user-images.githubusercontent.com/284612/44145561-b09397ea-a0a9-11e8-875c-33d9b47b39c9.gif)

1. Host (left in gif) clicks on an online user to invite them
2. This creates a Live Share session (if not already available) and sends the link over Slack
3. When the recipient (right in gif) receives the link, she gets prompted with join/ignore actions

These changes are WIP, over at #38. We could perhaps have a similar experience for reverse initiation. Personally, I haven't used the `/live request` command much, but that could just be me.

Also, we could show online users (as "users available for collab") in the new Live Share tree view, with a one-click action to invite them.

@lostintangent, would love to get your thoughts.

**Comment by lostintangent** [comment]
Closing this as resolved. We can always file new issues to address specific changes beyond the “/live request” command and new online users tree.
