### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by johnpapa** [karigari/vscode-chat#23]
Please include updates to the changelog for releases. This will help us know what is in them and help us know what to spread the word on when new features or bug fixes arive.

thanks for the great extension

**Comment by arjun27** [comment]
Sure! Will update the changelog from now on. 0.3.3 (will be released tomorrow) brings bot messages, so that you can see your CI updates right next to code. Here's a quick preview - would love to hear any feedback :)

<img width="1184" alt="screen shot 2018-07-03 at 12 04 56 am" src="https://user-images.githubusercontent.com/284612/42181189-a74d9fe2-7e57-11e8-9b00-8f97d0e7041b.png">

**Comment by arjun27** [comment]
Yes, these are regular slack messages. The extension doesn't render them as yet - 0.3.2 and previous versions only support only text messages. 0.3.3 will support bot messages, attachments, code snippets, to name a few.

My plan is to hook up the actions on these messages to open in the editor. For example, clicking a colleague's GitHub commit link will open the diff in the editor itself. Or a failed test log can be viewed right next to code. It'll reduce context switching and lead to more fluid communication in teams. How does that sound?
