### ISSUE TITLE
Massive privacy violation: automatically posts Live Share link in connected Discord

### ISSUE THREAD

**Issue by TAGC** [karigari/vscode-chat#246]
I installed the extension so that I could monitor chatrooms in a Discord guild through VS Code. I provided it with my private auth token, trusting that this would only be used to allow the extension to connect to Discord and not be abused.

Recently, I noticed I wasn't signed in on Live Share, so for the heck of it I signed in using my Microsoft work account while I was connected to Discord through VS Code. I found out later that a Live Share link had been posted automatically through my account in the Discord chat I was connected to, and that it had been there for hours. That link revealed my full name to anyone who followed it.

I'm not sure what exact version I had installed as I've now removed this extension, but it's likely the most recent one as of the time of writing. I'm using 64-bit Windows 10.

**Comment by arjun27** [comment]
Hi @TAGC - firstly, I apologize for this experience. I understand how this would have been a problem for you, and I want to take this seriously. Please let me understand how this happened, and we can then find a resolution that works.

The extension does not do such a thing by itself. My hypothesis is that this was caused by the one-click Live Share session initiation ([as given in the Readme](https://github.com/karigari/vscode-chat#with-slack-and-discord)) - which allows you to start a Live Share session with a contact/channel, and this then shares the invite with them. This gets triggered by clicking on the share icon next to the name of the channel.

If this is what happened, the user experience on the action should be improved, and we could add a confirmation to make it clear that it will share the LS link on the channel. That way, it would not be a surprise. I realize that it is actually very easy to accidentally click the icon, when one wants to click on the row to open the channel instead.

Again, apologies for the bad ux, and the unexpected outcome. It would be great if you could verify this, and I would then proceed to release a build with the fix

**Comment by TAGC** [comment]
Ah, that's probably it, yeah. I assumed that it had happened after I signed it, but it's probable it happened sometime after I'd signed it, and clicked that icon. Come to think of it, I probably did at some point, assuming it was meant to "pop open" the chat in a separate pane or something (I admit I didn't read the docs past "setup").

I can probably verify tomorrow by reinstalling, then going through the same steps.

**Comment by TAGC** [comment]
Okay, I verified that it doesn't post the link until you hit the "Invite to Live Share" button - my mistake.

> we could add a confirmation to make it clear that it will share the LS link on the channel

I think that would be nice, yeah.

**Comment by arjun27** [comment]
Thanks for verifying this @Tagc. I will add the confirmation to prevent this from happening again
