### ISSUE TITLE
Live share chat does not work

### ISSUE THREAD

**Issue by arjun27** [karigari/vscode-chat#247]
Reported by @ffxsam in https://github.com/MicrosoftDocs/live-share/issues/69#issuecomment-431487596

> It's a shame the chat extension doesn't work for me. The input box just says "Message undefined" and nothing works.

It looks like an initialization problem with the `vsls.SharedService`. We also know that the chat channel was not defined, which means the initialization failed before the channel setup.

@ffxsam - could you tell me if you were the guest or the host in this session? Also, which version of the live share extension was being used by you and the host?

**Comment by ffxsam** [comment]
I was doing a test by myself, with two VS Code instances. VS Live Share 0.3.834, and Team Chat 0.7.3.

**Comment by colshacol** [comment]
I came to create an issue for a very similar problem. (Doing my research first, I found https://github.com/MicrosoftDocs/live-share/issues/69#issuecomment-431487596 that lead me here.)

[Here is what I am experiencing.](https://youtu.be/garYPW0rOg4) (Video hosted on YouTube.)

Here is my VS-Code Insiders information:

<img width="421" alt="screen shot 2018-11-04 at 6 14 57 pm" src="https://user-images.githubusercontent.com/19484365/47972044-98816f80-e05d-11e8-8667-28150593ecda.png">

And my system:

<img width="590" alt="screen shot 2018-11-04 at 6 15 29 pm" src="https://user-images.githubusercontent.com/19484365/47972049-a505c800-e05d-11e8-8762-3420a8c35a49.png">

Here are the 2 reoccuring errors that repeatedly throw when I start LiveShare. (Seen in the video above.) They seem to happen intermittently, not when any specific action is taken.

<img width="961" alt="screen shot 2018-11-04 at 6 16 10 pm" src="https://user-images.githubusercontent.com/19484365/47972072-e1d1bf00-e05d-11e8-94af-34f7f9070fe3.png">

**Comment by arjun27** [comment]
Hey @colshacol - thank you for sharing the logs, they helped a lot. I have release v0.7.4 to the visual studio marketplace with a fix for this. This could have been prevented with better type checking and I'm investing in that effort in #260.

It is not clear to me why this is only affecting a few cases, and I want to get to the root cause. Did you clear the console logs before recording your screen cast? If so, would it be possible to share the logs generated from when VS Code was opened? My sense is that something went wrong during activation, which led to this issue downstream.

Thanks again for the logs!

**Comment by colshacol** [comment]
@arjun27 Yessir, you bet!

In the video provided, I had just updated Code (noticed it was behind), re-opened the window, and immediately opened devtools and cleared the jank unrelated to LiveShare.

The console output is quite heavy from start to finish, so I went ahead and created a second screen cast that covers opening Code, opening devtools, slowly scrolling pre-LiveShare output, opening LiveShare/chat, and tinkering.

I observed the following behaviors:

1. [The `find` error seems to be thrown on every `window.focus` event while the chat is open.](https://youtu.be/mVL2aGKZ--A?t=129)
2. I get an issue pertaining to `extensions.chat.updateMessages` when chat is opened.
3. I get an issue pertaining to `extensions.chat.sendMessage` when a message is sent.
2. `"cannot convert undefined or null to object"` happens when chat is opened _and_ closed. But the errors have slightly different traces.

When chat is opened:

<img width="958" alt="screen shot 2018-11-05 at 4 53 01 am" src="https://user-images.githubusercontent.com/19484365/47994150-10c84f00-e0b7-11e8-90b1-079b4add8bae.png">

When chat is closed:

<img width="960" alt="screen shot 2018-11-05 at 4 52 54 am" src="https://user-images.githubusercontent.com/19484365/47994151-10c84f00-e0b7-11e8-8f3b-daad9316c6c7.png">

[Again, the link to the updated, more thorough video is here.](https://youtu.be/mVL2aGKZ--A) (Forgive me for not un-hiding the entire console when I was scrolling the messages a few times. -_- I'm not very smart, haha.)

**Comment by colshacol** [comment]
Also, I am not sure if it auto-updated, but I was going to redo that latest video^ and _not_ cover up some of the logs with my editor, so I reloaded the window and all of a sudden LiveShare/chat worked fine.

**Comment by arjun27** [comment]
gotcha, thanks @colshacol, these logs help me validate the issue and the fix.

the extension must have auto-updated if its working for you. you can verify the installed version of the extension by opening the installed extensions list (cmd + shift + x on a Mac). the fixed version is 0.7.4

I'll close this issue as resolved then. let me know if there's any thing else I can help with.

**Comment by yoursdearboy** [comment]
I have this issue with 0.12.0 (Message undefined).

Also after selecting `> Chat with this user` the next error appears:
```
Cannot read property 'contactModel' of undefined
```

**Comment by arjun27** [comment]
Thanks for sharing @yoursdearboy. Will investigate and get back to you

**Comment by arjun27** [comment]
0.13.0 fixes an issue with the Live Share chat. Please give it a shot and let me know if it works for you!
