### ISSUE TITLE
[vscode] [slack] Invalid token

### ISSUE THREAD

**Issue by Takkiiii** [karigari/vscode-chat#275]
Token cannot be validated. Could you give some advice please?

- Extension Version: 0.8.2
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.30.0

**Comment by Takkiiii** [comment]
Hi @arjun27.
Sorry, my development environment is behind a network proxy.
I read it and I try it.
It worked without problems.
Thanks!
Close this issue. please.

**Comment by arjun27** [comment]
Awesome!

Btw, vscode 1.30 launched proxy support for all extensions. Would it be possible for you to enable that instead, and see if that works? Trying to collect feedback on how it works so as to recommend that - instead of a manual config. See more: https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions
