### ISSUE TITLE
Slack App Access & Permissions

### ISSUE THREAD

**Issue by challen0** [karigari/vscode-chat#397]
Can the Slack app access anything out of VS Code? I know it has access to content (messages, profiles, etc.) in the Slack workspace but couldn't find any information about the other direction.

**Comment by arjun27** [comment]
The Slack app does not access anything from inside VS Code. Let me lay down how the various pieces work to detail this out:

1/ The Team Chat extension is a VS Code extension that uses VS Code APIs - like to create a web view, show unread count in the status bar item. The extension can access VS Code content, since there are APIs for that. The extension is also fully open source, so you can see what API calls are being used.

2/ The extension works with multiple chat providers: Slack, Discord and VS Live Share. The extension uses APIs provided by these chat providers, and in the case of Slack, the extension uses authentication provided by the "Slack App" primitive. These API calls include sending/receiving messages, fetching unread counts, etc.

3/ The chat providers cannot access VS Code APIs directly, and are disconnected from the content inside the editor. In the future, we do want to make it easier for you to share things like "code snippets" in your chat thread - but these implementations will be sent as messages that are explicitly sent by the user over a chat provider API.

Hope this answers the question. Feel free to re-open if there's any other question
