### ISSUE TITLE
Messages are not sent to slack

### ISSUE THREAD

**Issue by mittalyashu** [karigari/vscode-chat#74]
![2018-08-31_10-59-56](https://user-images.githubusercontent.com/29014463/44894409-2fa01300-ad0d-11e8-8b88-4ac8ac81f966.gif)

**Comment by mittalyashu** [comment]
When I checked the list of app installed, there is no such app with the name `vscode-chat`.

![image](https://user-images.githubusercontent.com/29014463/44894476-860d5180-ad0d-11e8-8538-b5102184e9da.png)

**Comment by arjun27** [comment]
Thanks for reporting this @mittalyashu. 

1. For the messages issue: Currently, rendering the message only happens if the Slack API response for sending the message is successful. Which means this issue can happen if the API returns an error or if the network connection was flaky. We will be able to diagnose this better if you could send the contents of the output channel for Slack Chat.

<img width="775" alt="screen shot 2018-08-31 at 11 07 31 am" src="https://user-images.githubusercontent.com/284612/44894585-1a77b400-ad0e-11e8-939e-51e6c2b09e75.png">

2. For the installed apps issue: Can you share the link of this page? I use https://slack.com/apps/manage to check installed apps but that looks a bit different from your screenshot.

<img width="983" alt="screen shot 2018-08-31 at 11 10 16 am" src="https://user-images.githubusercontent.com/284612/44894694-adb0e980-ad0e-11e8-9cb1-c8215b10965c.png">

**Comment by mittalyashu** [comment]
Here's the screenshot of the output:

![image](https://user-images.githubusercontent.com/29014463/44895173-c15d4f80-ad10-11e8-8aef-52f09dba4bd4.png)

List of managed apps:

![image](https://user-images.githubusercontent.com/29014463/44895206-f8336580-ad10-11e8-82fb-d26085186afe.png)

@arjun27, if that API key gets public, doesn't anyone have access to the workspace.

**Comment by arjun27** [comment]
Thanks for sharing this Yashu. If I understand correctly, the token was revoked manually, after which sending the messages stopped working. On the messages side that is expected behavior - perhaps we could add a useful loader + error state in upcoming releases to improve the ux.

Yes, you are right to point out that the API key is sensitive. We should be storing that in the system keychain using [keytar](https://www.npmjs.com/package/keytar) to ensure that there is no unauthorized access. Adding keychain support is on my list of to-dos. Can you share why the token had to be revoked?

**Comment by mittalyashu** [comment]
> the token was revoked manually, after which sending the messages stopped working.

If the token was revoked manually or automatically, it should show/output some kind of error message in the UI of VS Code.

> Yes, you are right to point out that the API key is sensitive. We should be storing that in the system keychain using keytar to ensure that there is no unauthorized access. Adding keychain support is on my list of to-dos. 

You should not store the API key in the `settings.json` file. It is possible that people might use a extension like `sync setting` in that case, it is like sharing the API key in public.

If you any to hide the API for getting exposed, here what you can do.

You can see how [Sync Settings](https://github.com/shanalikhan/code-settings-sync) store the Gist token securely in VS Code _(not sure even that is the secure way to store the API keys or access token, I suggest you ask the VS Code for the same)_, without getting exposed. Sync Settings store the access token in `syncLocalSettings.json` inside `User` folder.

> Can you share why the token had to be revoked?

I got an email from slack.

![image](https://user-images.githubusercontent.com/29014463/44896435-d12b6280-ad15-11e8-94f7-2e007fc82e3c.png)

> We recently became aware that one or more authentication tokens for your Slack workspace, codecarrot.slack.com, have been posted publicly on the Internet. This can happen when a developer or other member of your organization posts their private token on a public forum or website (usually a code-sharing website like GitHub).

That my access token has been permanently disabled, that has happened becuase slack found out that my API is publicly available on Github since I was using `sync setting`.

**Comment by arjun27** [comment]
Yashu, thanks a lot for this explanation. I wasn't aware of how sync settings worked, but nevertheless, we need to move tokens to the system keychain (tracking in #77)

Is it possible for you to sign in with Slack again? Let me push keychain support and we can then set you back up with this

**Comment by mittalyashu** [comment]
> I wasn't aware of how sync settings worked

I have asked Shah khan in Slack

![chrome_2018-08-31_12-40-30](https://user-images.githubusercontent.com/29014463/44897959-1b631280-ad1b-11e8-8217-be2bded05aca.png)

> Is it possible for you to sign in with Slack again? 

Yeah, first I have to disable the `sync settings` and try.

> Let me push keychain support and we can then set you back up with this

What's this 😄?

**Comment by arjun27** [comment]
I'm working on keychain support so that we don't save anything in settings. Once that is released (should be done later today), I'd like for you to try signing in again.

**Comment by mittalyashu** [comment]
> I'd like for you to try signing in again.

It's working perfectly.

![2018-08-31_13-35-18](https://user-images.githubusercontent.com/29014463/44900661-cd520d00-ad22-11e8-9f71-268c06e2a9e0.png)

Do you know how to revoke the access token created by this extension?

**Comment by arjun27** [comment]
To revoke the app, you click on "Remove app" in this link: https://slack.com/apps/ACB4LQKN1-slack-chat-for-vs-code

**Comment by arjun27** [comment]
Quick update on this: the keychain improvements have been released with 0.5.8. The error message improvements will be tracked in #79. Will close this issue for now.
